title: PENG AO's blog
email: pengao@is.s.u-tokyo.ac.jp
github: https://github.com/PENG-AO
leetcode: https://leetcode.cn/u/peng_ao/
description: >
  Hi there, this is PENG AO, welcome to my site!<br>
  I'm a/an student/coder/reader/bodybuilder/traveler.

header_pages:
  - index.md
  - archive.html
  - profile.html

style: light
# listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

highlighter: rouge
markdown: kramdown
