title: PENG AO's blog
email: pengao[at]is.s.u-tokyo.ac.jp
github: https://github.com/PENG-AO
leetcode: https://leetcode.cn/u/peng_ao/

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 10
paginate_path: content/posts/page:num/

highlighter: none
markdown: kramdown
kramdown:
  header_offset: 1
  toc_levels: 1..3
  syntax_highlighter_opts:
    disable: true
