title: PENG AO's blog
email: pengao@is.s.u-tokyo.ac.jp
github: https://github.com/PENG-AO
leetcode: https://leetcode.cn/u/peng_ao/
description: Hi there, this is PENG AO, welcome to my site! I'm a student/coder/reader/bodybuilder/traveler.

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript

highlighter: none
markdown: kramdown
kramdown:
  header_offset: 1
  toc_levels: 1..3
  syntax_highlighter_opts:
    disable: true
