title: PENG AO's blog

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 8
paginate_path: /page:num/

highlighter: none
markdown: kramdown
kramdown:
  header_offset: 1
  toc_levels: 1..3
  syntax_highlighter_opts:
    disable: true
