title: PENG AO's blog
email: pengao@is.s.u-tokyo.ac.jp
github: https://github.com/PENG-AO
leetcode: https://leetcode.cn/u/peng_ao/
description: Hi there, this is PENG AO, welcome to my site! I'm a student/coder/reader/bodybuilder/traveler.

nav_pages:
  - home
  - album
  - footprint
  - profile

plugins:
  - jekyll-seo-tag

highlighter: none
markdown: kramdown
kramdown:
  header_offset: 1
  syntax_highlighter_opts:
    disable: true
